Mixer::stop was waiting indefinitely for thread to finish
didn't get all tests to pass
running 12 tests
test_input_remove: Pipeline state changed from Paused to Ready
test http::tests::test_input_list ... ok
test http::tests::test_input_get ... ok
test http::tests::test_input_remove ... ok
test http::tests::test_mixer_debug ... FAILED
test_mixer_create: Pipeline state changed from Null to Ready
test http::tests::test_mixer_create ... ok
test http::tests::test_input_add ... ok
test http::tests::test_mixer_get ... ok
test_mixer_list: Pipeline state changed from Ready to Paused
test http::tests::test_mixer_list ... ok
test http::tests::test_output_add ... ok
test_output_get: Pipeline state changed from Paused to Paused
test http::tests::test_output_get ... ok
test_output_list: Pipeline state changed from Playing to Paused
test http::tests::test_output_list ... ok
test_output_remove: Pipeline state changed from Paused to Playing
test http::tests::test_output_remove ... ok

failures:

---- http::tests::test_mixer_debug stdout ----
thread 'http::tests::test_mixer_debug' panicked at 'failed to execute process: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/http/handlers.rs:53:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

failures:
    http::tests::test_mixer_debug

test result: FAILED. 11 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--lib'